---
Description: "A task to configure vault"
Name: "vault-config"
Documentation: |
  Configures a vault backend (using consul for storage) for secret encryption
OptionalParams:
  - vault/server-count
  - vault/version
Templates:
  - ID: "vault.hcl.tmpl"
    Name: "Vault configuration"
    Path: "/etc/vault/vault.hcl"
  - ID: "vault-policy-transit-only.hcl.tmpl"
    Name: "Vault policy for transit backend"
    Path: "/etc/vault/policy-transit-only.hcl"  
  - ID: "vault-config.sh.tmpl"
    Name: "Configure vault"
    Path: ""    
Meta:
  icon: "book"
  color: "blue"
  title: "Community Content"
  feature-flags: "sane-exit-codes"
