---
Name: "krib/nginx-ingress-controller-container-image"
Description: "Custom container image to use for nginx ingress controller"
Documentation: |
  Allows operators to optionally override the container image used in the
  nginx-ingress-controller deployment. Possible use case would be pre-prepared images pushed to a 
  local trusted registry
  
Schema:
  type: "string"
Meta:
  color: "blue"
  icon: "setting"
  title: "Community Content"
