---
Name: "krib/ingress-nginx-mandatory"
Description: "Specifies the YAML config file url to use for nginx ingress install."
Documentation: |
  Set this string to an HTTP or HTTPS reference for a YAML configuration to
  use for nginx install.  
Schema:
  type: "string"
  default: "https://github.com/kubernetes/ingress-nginx/raw/nginx-0.25.1/deploy/static/mandatory.yaml"
Meta:
  color: "blue"
  icon: "ship"
  title: "Community Content"