---
Name: "provider/calico-config"
Description: "Calico config YAML to apply if using Calico Network Provider"
Documentation: |
  Set this string to an HTTP or HTTPS reference for a YAML configuration to
  use for the Calico network provider.  If Calico is not installed, this
  Param will have no effect on the cluster.
Schema:
  type: "string"
  default: "https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calicoctl.yaml"
Meta:
  color: "blue"
  icon: "ship"
  title: "Community Content"
